services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-wallet
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    depends_on:
      - db
      - rabbitmq
    networks:
      - wallet

  worker:
    build: .
    command: celery -A core worker -l INFO
    restart: always
    container_name: celery-wallet
    depends_on:
      - db
      - rabbitmq
    networks:
      - wallet

  db:
    container_name: postgres-wallet
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Dev1234@
      POSTGRES_DB: wallet
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wallet

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-wallet
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - wallet

volumes:
  pgdata:
  rabbitmq-data:

networks:
  wallet: