# Generated by Django 5.1.8 on 2025-04-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Imagem de perfil'),
        ),
    ]
