# Generated by Django 5.2 on 2025-05-05 19:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_img_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_image, verbose_name='Imagem de perfil'),
        ),
    ]
